---
user: jpaul
downloads: ~/.ansible-downloads/

configure_dotfiles: yes
configure_sudoers: yes
configure_osx: yes

dotfiles_repo: https://github.com/jayson/dotfiles
dotfiles_repo_local_destinationdotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/projects/dotfiles
dotfiles_files:
  - .bash_profile
  - .gitignore
  - .inputrc
  - .osx
  - .vimrc

homebrew_installed_packages:
  # - ansible # Installed via Pip.
  - python
  - cfssl
  - ctags
  - dockutil
  - fzf
  - git
  - gpg
  - kubernetes-cli
  - mas
  - node
  - rbenv
  - readline
  - ruby
  - the_silver_searcher
  - vim
  - watch
  - wget

homebrew_taps:
  - homebrew/core
  - caskroom/cask
  - caskroom/fonts

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - docker
  - alfred
  - google-chrome
  - slack
  - vagrant
  - virtualbox
  - iterm2
  - fantastical
  - spectacle
  - dashlane
  - font-robotomono-nerd-font

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_apps: []
mas_email: "jaysonpaul@gmail.com"
mas_password: ""

osx_script: "~/.osx --no-restart"

gem_packages:
  - name: bundler
    state: present  # present/absent/latest, default: present

composer_packages: []
npm_packages: []
pip_packages: []
# TODO: special virtualenv setup

dockitems_to_remove:
  - Launchpad
  - Contacts
  - Notes
  - Reminders
  - Maps
  - Pages
  - Photos
  - FaceTime
  - iBooks
  - App Store
  - System Preferences
  - Downloads

dockitems_to_persist:
  - name: Notes
    path: /Applications/Notes.app
    position: 1
  - name: iTerm
    path: /Applications/iTerm.app
    position: 2
  - name: Fantastical 2
    path: /Applications/Fantastical 2.app
    position: 3
  - name: Google Chrome
    path: /Applications/Google Chrome.app
    position: 4
  - name: Slack
    path: /Applications/Slack.app
    position: 5


# Glob pattern to ansible task files to run after all other tasks are finished.
post_provision_tasks: []
